language: python

python:
  - 2.8

install:
  - pip install coveralls

script:
  - coverage run --source=hoge_test setup.py test

after_success:
  - coveralls

notifications:
  slack:
    secure: your_token_key