language: python

python:
  - 2.7

install:
  - pip install coveralls

script:
  - coverage run --source=test_fuga setup.py test

after_success:
  - coveralls

notifications:
  slack:
    secure: your_token_key